# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.srcs/sources_1/bd/cordic_test/ip/cordic_test_ila_0_0/cordic_test_ila_0_0.xci
# IP: The module: 'cordic_test_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.gen/sources_1/bd/cordic_test/ip/cordic_test_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_test_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.gen/sources_1/bd/cordic_test/ip/cordic_test_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_test_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.gen/sources_1/bd/cordic_test/ip/cordic_test_ila_0_0/cordic_test_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_test_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.srcs/sources_1/bd/cordic_test/ip/cordic_test_ila_0_0/cordic_test_ila_0_0.xci
# IP: The module: 'cordic_test_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.gen/sources_1/bd/cordic_test/ip/cordic_test_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_test_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.gen/sources_1/bd/cordic_test/ip/cordic_test_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_test_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.gen/sources_1/bd/cordic_test/ip/cordic_test_ila_0_0/cordic_test_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_test_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
