# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cordic_test/cordic_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_test || ORIG_REF_NAME==cordic_test} -quiet] -quiet

# IP: bd/cordic_test/ip/cordic_test_processing_system7_0_0/cordic_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_test_processing_system7_0_0 || ORIG_REF_NAME==cordic_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/cordic_test/ip/cordic_test_coordic_axi_custom_0_0/cordic_test_coordic_axi_custom_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_test_coordic_axi_custom_0_0 || ORIG_REF_NAME==cordic_test_coordic_axi_custom_0_0} -quiet] -quiet

# IP: bd/cordic_test/ip/cordic_test_auto_pc_0/cordic_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_test_auto_pc_0 || ORIG_REF_NAME==cordic_test_auto_pc_0} -quiet] -quiet

# IP: bd/cordic_test/ip/cordic_test_ps7_0_axi_periph_0/cordic_test_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==cordic_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cordic_test/ip/cordic_test_rst_ps7_0_100M_0/cordic_test_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==cordic_test_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cordic_test/ip/cordic_test_ila_0_0/cordic_test_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_test_ila_0_0 || ORIG_REF_NAME==cordic_test_ila_0_0} -quiet] -quiet

# XDC: /home/gvaldez/microarquitecturas_softcore/trabajo_final_mys/sintesis/testing_coordic_alg/testing_coordic_alg.gen/sources_1/bd/cordic_test/cordic_test_ooc.xdc
